### PR TITLE
Update backend

### PR DESCRIPTION
**Pull request by mcardenas389**
Modified code so that table name isn't hard coded.

### CODE REVIEW

**Comment by verahuang** [comment]
In InputCheck.java, the code in method getSigFigs(String in) under comment "remove trailing zero's if not a decimal" is not appropriate. The 0s in the integer could be significant. Usually the data in this case should be express using scientific notation. For example, 32500 cm should be expressed as 3.25 x 10^4 cm, 3.250 x 10^4 cm or 3.2500 x 10^4 cm depending on the precision of the equipment. That it the number of significant figures could be 3, 4 or 5. So if there is no decimal point and has trailing 0s in the integer part, the data is incorrectly recorded.

**Comment by verahuang** [comment]
In lab0_1Checks.java, if j==2, it is on the "Number of S.F." column. Why is the number of s.f for data[i][j] needs to add 3?

**Comment by mcardenas389** [comment]
That was based on what was written in the most recent Lab1 spreadsheet on google docs. The formula for checking significant figures is written in F17, where it states:

"How to check the correctness for the number of significant figures: 
1. Look at the data entered in the ""Weight"" column and find out how many digit on the left of the decimal point - suppose there are x number of digits. 
2. If it is measured using the quadruple beam balance, it should have 3 decimal places. Therefore, the number of significant figures should be 3 + x. 
3. If it is measured using the analytical balance, it should have 4 decimal places. Therefore, the number of significant figures should be 4 + x. "

But I can see that there have was a slight error on my part since I'm adding s.f.'s together instead of number of digits with s.f.'s as stated here. Will fix this.

**Comment by verahuang** [comment]
but the getSigFigs(String int) returns the total number of s.f. including the decimal places.

**Comment by mcardenas389** [comment]
So you just want to go by the result of getSigFigs() and not add anything to the value?

**Comment by verahuang** [comment]
To get the correct s.f. for data[i][j], write a method in the InputCheck.java to get the integer part of a measured or calculated data, then add the correct number of decimal places.
The getSigFigs(String int) method should return the number of s.f. the student entered. Compare this with the correct number of s.f. would tell if the data entered by students is correct.

**Comment by verahuang** [comment]
I should say in my previous comment that "The getSigFigs(String int) method should return the number of s.f. the student entered data".

**Comment by mcardenas389** [comment]
Yeah, that makes sense. Sorry for the confusion, I'll make the corrections now.

**Pull request closed without merging**
